// Auto-generated by LibreLane
module alu(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clock,
  input reset,
  input start_port,
  input[31:0] a,
  input[31:0] b,
  input[7:0] opcode,
  output done_port,
  output[31:0] return_port
);
endmodule
