/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-03 10:01:32
*/
`include "custom_cells.v"
`include "LUT_netlist.v.chained.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \sin ;
    reg[1:0] \shift_amt ;
    reg[0:0] \shift ;
    reg[0:0] \clk ;
    wire[0:0] \y ;
    reg[0:0] \rst_n ;
    reg[0:0] \is_sync ;
    wire[0:0] \sout ;
    reg[0:0] \tck ;
    reg[0:0] \test ;
    reg[1:0] \in ;

        always #(`CLOCK_PERIOD / 2) clk = ~clk; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    LUT uut(
        .\sin ( \sin ) , .\shift_amt ( \shift_amt ) , .\shift ( \shift ) , .\clk ( \clk ) , .\y ( \y ) , .\rst_n ( \rst_n ) , .\is_sync ( \is_sync ) , .\sout ( \sout ) , .\tck ( \tck ) , .\test ( \test ) , .\in ( \in ) 
    ); 

    wire[6:0] __serializable__ =
        7'b0010111;
    reg[6:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \clk = 0 ;
        \rst_n = 0 ;
        \in = 0 ;
        \shift_amt = 0 ;
        \is_sync = 0 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #(`CLOCK_PERIOD*5);
        rst_n = ~rst_n;
        shift = 1;
        test = 1;
        for (i = 0; i < 7; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 7; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
