/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-03 11:20:29
*/
/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module LUT(clk, rst_n, in, shift_amt, is_sync, y, tms, tck, tdi, tdo, trst, tdo_paden_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire \__dut__._00_ ;
  wire \__dut__._01_ ;
  wire \__dut__._02_ ;
  wire \__dut__._03_ ;
  wire \__dut__._04_ ;
  wire \__dut__._05_ ;
  wire \__dut__._06_ ;
  wire \__dut__.__BoundaryScanRegister_input__0__.dout ;
  wire \__dut__.__BoundaryScanRegister_input__0__.sout ;
  wire \__dut__.__BoundaryScanRegister_input__1__.dout ;
  wire \__dut__.__BoundaryScanRegister_input__1__.sout ;
  wire \__dut__.__BoundaryScanRegister_input__2__.dout ;
  wire \__dut__.__BoundaryScanRegister_input__2__.sout ;
  wire \__dut__.__BoundaryScanRegister_input__3__.dout ;
  wire \__dut__.__BoundaryScanRegister_input__3__.sout ;
  wire \__dut__.__BoundaryScanRegister_input__4__.dout ;
  wire \__dut__.__BoundaryScanRegister_input__4__.sout ;
  wire \__dut__.__BoundaryScanRegister_output__5__.sin ;
  wire \__dut__.__uuf__._0_ ;
  wire \__dut__.__uuf__.__clk_source__ ;
  wire \__dut__.__uuf__.comb_y ;
  wire \__dut__.shift ;
  wire \__dut__.sout ;
  wire \__dut__.test ;
  wire \__tap_wrapper__.__tap_top__.bypass_reg ;
  wire \__tap_wrapper__.__tap_top__.bypassed_tdo ;
  wire \__tap_wrapper__.__tap_top__.capture_dr ;
  wire \__tap_wrapper__.__tap_top__.capture_ir ;
  wire \__tap_wrapper__.__tap_top__.exit1_dr ;
  wire \__tap_wrapper__.__tap_top__.exit1_ir ;
  wire \__tap_wrapper__.__tap_top__.exit2_dr ;
  wire \__tap_wrapper__.__tap_top__.exit2_ir ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[0] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[10] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[11] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[12] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[13] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[14] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[15] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[16] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[17] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[18] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[19] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[1] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[20] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[21] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[22] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[23] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[24] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[25] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[26] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[27] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[28] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[29] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[2] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[30] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[31] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[3] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[4] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[5] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[6] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[7] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[8] ;
  wire \__tap_wrapper__.__tap_top__.idcode_reg[9] ;
  wire \__tap_wrapper__.__tap_top__.idcode_tdo ;
  wire \__tap_wrapper__.__tap_top__.instruction_tdo ;
  wire \__tap_wrapper__.__tap_top__.jtag_ir[0] ;
  wire \__tap_wrapper__.__tap_top__.jtag_ir[1] ;
  wire \__tap_wrapper__.__tap_top__.jtag_ir[2] ;
  wire \__tap_wrapper__.__tap_top__.jtag_ir[3] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[0] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[1] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[2] ;
  wire \__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[3] ;
  wire \__tap_wrapper__.__tap_top__.pause_dr ;
  wire \__tap_wrapper__.__tap_top__.pause_ir ;
  wire \__tap_wrapper__.__tap_top__.run_test_idle ;
  wire \__tap_wrapper__.__tap_top__.select_dr_scan ;
  wire \__tap_wrapper__.__tap_top__.select_ir_scan ;
  wire \__tap_wrapper__.__tap_top__.shift_dr ;
  wire \__tap_wrapper__.__tap_top__.shift_ir ;
  wire \__tap_wrapper__.__tap_top__.shift_ir_neg ;
  wire \__tap_wrapper__.__tap_top__.tdo_padoe_o ;
  wire \__tap_wrapper__.__tap_top__.test_logic_reset ;
  wire \__tap_wrapper__.__tap_top__.tms_q1 ;
  wire \__tap_wrapper__.__tap_top__.tms_q2 ;
  wire \__tap_wrapper__.__tap_top__.tms_q3 ;
  wire \__tap_wrapper__.__tap_top__.tms_q4 ;
  wire \__tap_wrapper__.__tap_top__.update_dr ;
  wire \__tap_wrapper__.__tap_top__.update_ir ;
  input clk;
  wire clk;
  input [1:0] in;
  wire [1:0] in;
  input is_sync;
  wire is_sync;
  input rst_n;
  wire rst_n;
  input [1:0] shift_amt;
  wire [1:0] shift_amt;
  input tck;
  wire tck;
  input tdi;
  wire tdi;
  output tdo;
  wire tdo;
  output tdo_paden_o;
  wire tdo_paden_o;
  input tms;
  wire tms;
  input trst;
  wire trst;
  output y;
  wire y;
  sky130_fd_sc_hd__clkinv_1 _101_ (
    .A(tck),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _102_ (
    .A(\__tap_wrapper__.__tap_top__.tdo_padoe_o ),
    .Y(tdo_paden_o)
  );
  sky130_fd_sc_hd__clkinv_1 _103_ (
    .A(\__tap_wrapper__.__tap_top__.test_logic_reset ),
    .Y(\__dut__.test )
  );
  sky130_fd_sc_hd__clkinv_1 _104_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_tdo ),
    .Y(_067_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _105_ (
    .A(\__tap_wrapper__.__tap_top__.jtag_ir[0] ),
    .SLEEP(\__tap_wrapper__.__tap_top__.shift_ir ),
    .X(_068_)
  );
  sky130_fd_sc_hd__a211o_1 _106_ (
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[1] ),
    .A2(\__tap_wrapper__.__tap_top__.shift_ir ),
    .B1(_068_),
    .C1(\__tap_wrapper__.__tap_top__.capture_ir ),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2i_1 _107_ (
    .A0(\__tap_wrapper__.__tap_top__.jtag_ir[1] ),
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[2] ),
    .S(\__tap_wrapper__.__tap_top__.shift_ir ),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(\__tap_wrapper__.__tap_top__.capture_ir ),
    .B(_069_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _109_ (
    .A(\__tap_wrapper__.__tap_top__.jtag_ir[2] ),
    .SLEEP(\__tap_wrapper__.__tap_top__.shift_ir ),
    .X(_070_)
  );
  sky130_fd_sc_hd__a211o_1 _110_ (
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[3] ),
    .A2(\__tap_wrapper__.__tap_top__.shift_ir ),
    .B1(_070_),
    .C1(\__tap_wrapper__.__tap_top__.capture_ir ),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2i_1 _111_ (
    .A0(\__tap_wrapper__.__tap_top__.jtag_ir[3] ),
    .A1(tdi),
    .S(\__tap_wrapper__.__tap_top__.shift_ir ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _112_ (
    .A(\__tap_wrapper__.__tap_top__.capture_ir ),
    .B(_071_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__and3_1 _113_ (
    .A(tms),
    .B(\__tap_wrapper__.__tap_top__.tms_q3 ),
    .C(\__tap_wrapper__.__tap_top__.tms_q1 ),
    .X(_072_)
  );
  sky130_fd_sc_hd__and3_1 _114_ (
    .A(\__tap_wrapper__.__tap_top__.tms_q4 ),
    .B(\__tap_wrapper__.__tap_top__.tms_q2 ),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand3_1 _115_ (
    .A(\__tap_wrapper__.__tap_top__.tms_q4 ),
    .B(\__tap_wrapper__.__tap_top__.tms_q2 ),
    .C(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__mux2i_1 _116_ (
    .A0(\__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ),
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[0] ),
    .S(\__tap_wrapper__.__tap_top__.update_ir ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(_073_),
    .B(_075_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__mux2i_1 _118_ (
    .A0(\__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ),
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[1] ),
    .S(\__tap_wrapper__.__tap_top__.update_ir ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(_074_),
    .B(_076_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__mux2i_1 _120_ (
    .A0(\__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ),
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[2] ),
    .S(\__tap_wrapper__.__tap_top__.update_ir ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _121_ (
    .A(_073_),
    .B(_077_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__mux2i_1 _122_ (
    .A0(\__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ),
    .A1(\__tap_wrapper__.__tap_top__.jtag_ir[3] ),
    .S(\__tap_wrapper__.__tap_top__.update_ir ),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _123_ (
    .A(_073_),
    .B(_078_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(\__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ),
    .B(\__tap_wrapper__.__tap_top__.shift_dr ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor4_1 _125_ (
    .A(\__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ),
    .B(\__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ),
    .C(\__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ),
    .D(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2b_1 _126_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[1] ),
    .B(_080_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2b_1 _127_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[2] ),
    .B(_080_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__and2_0 _128_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[3] ),
    .B(_080_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_0 _129_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[4] ),
    .B(_080_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_0 _130_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[5] ),
    .B(_080_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_0 _131_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[6] ),
    .B(_080_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2b_1 _132_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[7] ),
    .B(_080_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2b_1 _133_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[8] ),
    .B(_080_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2b_1 _134_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[9] ),
    .B(_080_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__and2_0 _135_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[10] ),
    .B(_080_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_0 _136_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[11] ),
    .B(_080_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_0 _137_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[12] ),
    .B(_080_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _138_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[13] ),
    .B(_080_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__and2_0 _139_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[14] ),
    .B(_080_),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_0 _140_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[15] ),
    .B(_080_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and2_0 _141_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[16] ),
    .B(_080_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _142_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[17] ),
    .B(_080_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__and2_0 _143_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[18] ),
    .B(_080_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2b_1 _144_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[19] ),
    .B(_080_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__and2_0 _145_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[20] ),
    .B(_080_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2b_1 _146_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[21] ),
    .B(_080_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and2_0 _147_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[22] ),
    .B(_080_),
    .X(_038_)
  );
  sky130_fd_sc_hd__and2_0 _148_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[23] ),
    .B(_080_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2b_1 _149_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[24] ),
    .B(_080_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__and2_0 _150_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[25] ),
    .B(_080_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2_0 _151_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[26] ),
    .B(_080_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2b_1 _152_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[27] ),
    .B(_080_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__and2_0 _153_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[28] ),
    .B(_080_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2b_1 _154_ (
    .A_N(\__tap_wrapper__.__tap_top__.idcode_reg[29] ),
    .B(_080_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__and2_0 _155_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[30] ),
    .B(_080_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and2_0 _156_ (
    .A(\__tap_wrapper__.__tap_top__.idcode_reg[31] ),
    .B(_080_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and2_0 _157_ (
    .A(tdi),
    .B(_080_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _158_ (
    .A0(\__tap_wrapper__.__tap_top__.bypass_reg ),
    .A1(tdi),
    .S(\__tap_wrapper__.__tap_top__.shift_dr ),
    .X(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _159_ (
    .A1(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[0] ),
    .A2(\__dut__.sout ),
    .B1(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[3] ),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o21ai_0 _160_ (
    .A1(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[0] ),
    .A2(_067_),
    .B1(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[1] ),
    .A2(_082_),
    .B1(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[2] ),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[3] ),
    .B(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[2] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _163_ (
    .A(\__tap_wrapper__.__tap_top__.bypassed_tdo ),
    .B(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(\__tap_wrapper__.__tap_top__.instruction_tdo ),
    .B(\__tap_wrapper__.__tap_top__.shift_ir_neg ),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o31ai_1 _165_ (
    .A1(\__tap_wrapper__.__tap_top__.shift_ir_neg ),
    .A2(_083_),
    .A3(_085_),
    .B1(_086_),
    .Y(tdo)
  );
  sky130_fd_sc_hd__o21ai_0 _166_ (
    .A1(\__tap_wrapper__.__tap_top__.test_logic_reset ),
    .A2(\__tap_wrapper__.__tap_top__.select_ir_scan ),
    .B1(tms),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(_074_),
    .B(_087_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _168_ (
    .A(\__tap_wrapper__.__tap_top__.update_ir ),
    .B(\__tap_wrapper__.__tap_top__.run_test_idle ),
    .C(\__tap_wrapper__.__tap_top__.update_dr ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21oi_1 _169_ (
    .A1(\__dut__.test ),
    .A2(_088_),
    .B1(tms),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(tms),
    .B(_074_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(_088_),
    .B(_089_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _172_ (
    .A(\__tap_wrapper__.__tap_top__.select_dr_scan ),
    .SLEEP(tms),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _173_ (
    .A(\__tap_wrapper__.__tap_top__.shift_dr ),
    .B(\__tap_wrapper__.__tap_top__.capture_dr ),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor3_1 _174_ (
    .A(\__tap_wrapper__.__tap_top__.shift_dr ),
    .B(\__tap_wrapper__.__tap_top__.exit2_dr ),
    .C(\__tap_wrapper__.__tap_top__.capture_dr ),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _175_ (
    .A(tms),
    .B(_091_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_089_),
    .B(_090_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(\__tap_wrapper__.__tap_top__.exit1_dr ),
    .B(\__tap_wrapper__.__tap_top__.pause_dr ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(tms),
    .B(_092_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__and3_1 _179_ (
    .A(tms),
    .B(\__tap_wrapper__.__tap_top__.pause_dr ),
    .C(_074_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(\__tap_wrapper__.__tap_top__.exit2_dr ),
    .B(\__tap_wrapper__.__tap_top__.exit1_dr ),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_089_),
    .B(_093_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__and3_1 _182_ (
    .A(tms),
    .B(\__tap_wrapper__.__tap_top__.select_dr_scan ),
    .C(_074_),
    .X(_060_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _183_ (
    .A(\__tap_wrapper__.__tap_top__.select_ir_scan ),
    .SLEEP(tms),
    .X(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(\__tap_wrapper__.__tap_top__.capture_ir ),
    .B(\__tap_wrapper__.__tap_top__.shift_ir ),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor3_1 _185_ (
    .A(\__tap_wrapper__.__tap_top__.capture_ir ),
    .B(\__tap_wrapper__.__tap_top__.shift_ir ),
    .C(\__tap_wrapper__.__tap_top__.exit2_ir ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(tms),
    .B(_095_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _187_ (
    .A(_089_),
    .B(_094_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(\__tap_wrapper__.__tap_top__.exit1_ir ),
    .B(\__tap_wrapper__.__tap_top__.pause_ir ),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(tms),
    .B(_096_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__and3_1 _190_ (
    .A(tms),
    .B(\__tap_wrapper__.__tap_top__.pause_ir ),
    .C(_074_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(\__tap_wrapper__.__tap_top__.exit2_ir ),
    .B(\__tap_wrapper__.__tap_top__.exit1_ir ),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_089_),
    .B(_097_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(\__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ),
    .B(\__tap_wrapper__.__tap_top__.pause_dr ),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor4_1 _194_ (
    .A(\__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ),
    .B(\__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ),
    .C(\__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ),
    .D(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__or4_1 _195_ (
    .A(\__tap_wrapper__.__tap_top__.shift_dr ),
    .B(\__tap_wrapper__.__tap_top__.shift_ir ),
    .C(\__tap_wrapper__.__tap_top__.exit2_dr ),
    .D(_099_),
    .X(_063_)
  );
  sky130_fd_sc_hd__o31ai_1 _196_ (
    .A1(\__tap_wrapper__.__tap_top__.shift_dr ),
    .A2(\__tap_wrapper__.__tap_top__.exit1_dr ),
    .A3(\__tap_wrapper__.__tap_top__.pause_dr ),
    .B1(\__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4b_1 _197_ (
    .A(\__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ),
    .B(\__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ),
    .C(_100_),
    .D_N(\__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ),
    .Y(\__dut__.shift )
  );
  sky130_fd_sc_hd__clkinv_1 _198_ (
    .A(tck),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _199_ (
    .A(tck),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _200_ (
    .A(tck),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _201_ (
    .A(tck),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(tck),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _203_ (
    .A(tck),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _204_ (
    .A(tck),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _205_ (
    .A(tck),
    .Y(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _206_ (
    .CLK(tck),
    .D(_009_),
    .Q(\__tap_wrapper__.__tap_top__.jtag_ir[0] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _207_ (
    .CLK(tck),
    .D(_010_),
    .Q(\__tap_wrapper__.__tap_top__.jtag_ir[1] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _208_ (
    .CLK(tck),
    .D(_011_),
    .Q(\__tap_wrapper__.__tap_top__.jtag_ir[2] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _209_ (
    .CLK(tck),
    .D(_012_),
    .Q(\__tap_wrapper__.__tap_top__.jtag_ir[3] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _210_ (
    .CLK(tck),
    .D(_053_),
    .Q(\__tap_wrapper__.__tap_top__.exit1_ir ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _211_ (
    .CLK(tck),
    .D(_057_),
    .Q(\__tap_wrapper__.__tap_top__.pause_ir ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _212_ (
    .CLK(tck),
    .D(_055_),
    .Q(\__tap_wrapper__.__tap_top__.exit2_ir ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _213_ (
    .CLK(tck),
    .D(_066_),
    .Q(\__tap_wrapper__.__tap_top__.update_ir ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _214_ (
    .CLK(tck),
    .D(_013_),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfstp_2 _215_ (
    .CLK(tck),
    .D(_014_),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ),
    .SET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(tck),
    .D(_015_),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _217_ (
    .CLK(tck),
    .D(_016_),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(_000_),
    .D(\__tap_wrapper__.__tap_top__.jtag_ir[0] ),
    .Q(\__tap_wrapper__.__tap_top__.instruction_tdo )
  );
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(_001_),
    .D(\__tap_wrapper__.__tap_top__.idcode_reg[0] ),
    .Q(\__tap_wrapper__.__tap_top__.idcode_tdo )
  );
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(tck),
    .D(_017_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(tck),
    .D(_018_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(tck),
    .D(_019_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(tck),
    .D(_020_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(tck),
    .D(_021_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(tck),
    .D(_022_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _226_ (
    .CLK(tck),
    .D(_023_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _227_ (
    .CLK(tck),
    .D(_024_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _228_ (
    .CLK(tck),
    .D(_025_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _229_ (
    .CLK(tck),
    .D(_026_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _230_ (
    .CLK(tck),
    .D(_027_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[10] )
  );
  sky130_fd_sc_hd__dfxtp_1 _231_ (
    .CLK(tck),
    .D(_028_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[11] )
  );
  sky130_fd_sc_hd__dfxtp_1 _232_ (
    .CLK(tck),
    .D(_029_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[12] )
  );
  sky130_fd_sc_hd__dfxtp_1 _233_ (
    .CLK(tck),
    .D(_030_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[13] )
  );
  sky130_fd_sc_hd__dfxtp_1 _234_ (
    .CLK(tck),
    .D(_031_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[14] )
  );
  sky130_fd_sc_hd__dfxtp_1 _235_ (
    .CLK(tck),
    .D(_032_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[15] )
  );
  sky130_fd_sc_hd__dfxtp_1 _236_ (
    .CLK(tck),
    .D(_033_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[16] )
  );
  sky130_fd_sc_hd__dfxtp_1 _237_ (
    .CLK(tck),
    .D(_034_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[17] )
  );
  sky130_fd_sc_hd__dfxtp_1 _238_ (
    .CLK(tck),
    .D(_035_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[18] )
  );
  sky130_fd_sc_hd__dfxtp_1 _239_ (
    .CLK(tck),
    .D(_036_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[19] )
  );
  sky130_fd_sc_hd__dfxtp_1 _240_ (
    .CLK(tck),
    .D(_037_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[20] )
  );
  sky130_fd_sc_hd__dfxtp_1 _241_ (
    .CLK(tck),
    .D(_038_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[21] )
  );
  sky130_fd_sc_hd__dfxtp_1 _242_ (
    .CLK(tck),
    .D(_039_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[22] )
  );
  sky130_fd_sc_hd__dfxtp_1 _243_ (
    .CLK(tck),
    .D(_040_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[23] )
  );
  sky130_fd_sc_hd__dfxtp_1 _244_ (
    .CLK(tck),
    .D(_041_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[24] )
  );
  sky130_fd_sc_hd__dfxtp_1 _245_ (
    .CLK(tck),
    .D(_042_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[25] )
  );
  sky130_fd_sc_hd__dfxtp_1 _246_ (
    .CLK(tck),
    .D(_043_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[26] )
  );
  sky130_fd_sc_hd__dfxtp_1 _247_ (
    .CLK(tck),
    .D(_044_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[27] )
  );
  sky130_fd_sc_hd__dfxtp_1 _248_ (
    .CLK(tck),
    .D(_045_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[28] )
  );
  sky130_fd_sc_hd__dfxtp_1 _249_ (
    .CLK(tck),
    .D(_046_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[29] )
  );
  sky130_fd_sc_hd__dfxtp_1 _250_ (
    .CLK(tck),
    .D(_047_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[30] )
  );
  sky130_fd_sc_hd__dfxtp_1 _251_ (
    .CLK(tck),
    .D(_048_),
    .Q(\__tap_wrapper__.__tap_top__.idcode_reg[31] )
  );
  sky130_fd_sc_hd__dfxtp_1 _252_ (
    .CLK(_002_),
    .D(\__tap_wrapper__.__tap_top__.bypass_reg ),
    .Q(\__tap_wrapper__.__tap_top__.bypassed_tdo )
  );
  sky130_fd_sc_hd__dfrtp_1 _253_ (
    .CLK(tck),
    .D(_049_),
    .Q(\__tap_wrapper__.__tap_top__.bypass_reg ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfxtp_1 _254_ (
    .CLK(_003_),
    .D(_063_),
    .Q(\__tap_wrapper__.__tap_top__.tdo_padoe_o )
  );
  sky130_fd_sc_hd__dfxtp_1 _255_ (
    .CLK(_004_),
    .D(\__tap_wrapper__.__tap_top__.latched_jtag_ir[0] ),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _256_ (
    .CLK(_005_),
    .D(\__tap_wrapper__.__tap_top__.latched_jtag_ir[1] ),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _257_ (
    .CLK(_006_),
    .D(\__tap_wrapper__.__tap_top__.latched_jtag_ir[2] ),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _258_ (
    .CLK(_007_),
    .D(\__tap_wrapper__.__tap_top__.latched_jtag_ir[3] ),
    .Q(\__tap_wrapper__.__tap_top__.latched_jtag_ir_neg[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _259_ (
    .CLK(_008_),
    .D(\__tap_wrapper__.__tap_top__.shift_ir ),
    .Q(\__tap_wrapper__.__tap_top__.shift_ir_neg )
  );
  sky130_fd_sc_hd__dfxtp_1 _260_ (
    .CLK(tck),
    .D(\__tap_wrapper__.__tap_top__.tms_q3 ),
    .Q(\__tap_wrapper__.__tap_top__.tms_q4 )
  );
  sky130_fd_sc_hd__dfxtp_1 _261_ (
    .CLK(tck),
    .D(\__tap_wrapper__.__tap_top__.tms_q2 ),
    .Q(\__tap_wrapper__.__tap_top__.tms_q3 )
  );
  sky130_fd_sc_hd__dfxtp_1 _262_ (
    .CLK(tck),
    .D(\__tap_wrapper__.__tap_top__.tms_q1 ),
    .Q(\__tap_wrapper__.__tap_top__.tms_q2 )
  );
  sky130_fd_sc_hd__dfxtp_1 _263_ (
    .CLK(tck),
    .D(tms),
    .Q(\__tap_wrapper__.__tap_top__.tms_q1 )
  );
  sky130_fd_sc_hd__dfstp_2 _264_ (
    .CLK(tck),
    .D(_064_),
    .Q(\__tap_wrapper__.__tap_top__.test_logic_reset ),
    .SET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _265_ (
    .CLK(tck),
    .D(_058_),
    .Q(\__tap_wrapper__.__tap_top__.run_test_idle ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _266_ (
    .CLK(tck),
    .D(_059_),
    .Q(\__tap_wrapper__.__tap_top__.select_dr_scan ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _267_ (
    .CLK(tck),
    .D(_050_),
    .Q(\__tap_wrapper__.__tap_top__.capture_dr ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _268_ (
    .CLK(tck),
    .D(_061_),
    .Q(\__tap_wrapper__.__tap_top__.shift_dr ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _269_ (
    .CLK(tck),
    .D(_052_),
    .Q(\__tap_wrapper__.__tap_top__.exit1_dr ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _270_ (
    .CLK(tck),
    .D(_056_),
    .Q(\__tap_wrapper__.__tap_top__.pause_dr ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _271_ (
    .CLK(tck),
    .D(_054_),
    .Q(\__tap_wrapper__.__tap_top__.exit2_dr ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _272_ (
    .CLK(tck),
    .D(_065_),
    .Q(\__tap_wrapper__.__tap_top__.update_dr ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _273_ (
    .CLK(tck),
    .D(_060_),
    .Q(\__tap_wrapper__.__tap_top__.select_ir_scan ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _274_ (
    .CLK(tck),
    .D(_051_),
    .Q(\__tap_wrapper__.__tap_top__.capture_ir ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__dfrtp_1 _275_ (
    .CLK(tck),
    .D(_062_),
    .Q(\__tap_wrapper__.__tap_top__.shift_ir ),
    .RESET_B(trst)
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._07_  (
    .A0(in[0]),
    .A1(\__dut__.__BoundaryScanRegister_input__0__.sout ),
    .S(\__dut__.test ),
    .X(\__dut__.__BoundaryScanRegister_input__0__.dout )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._08_  (
    .A0(\__dut__.__BoundaryScanRegister_input__0__.dout ),
    .A1(tdi),
    .S(\__dut__.shift ),
    .X(\__dut__._00_ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._09_  (
    .A0(in[1]),
    .A1(\__dut__.__BoundaryScanRegister_input__1__.sout ),
    .S(\__dut__.test ),
    .X(\__dut__.__BoundaryScanRegister_input__1__.dout )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._10_  (
    .A0(\__dut__.__BoundaryScanRegister_input__1__.dout ),
    .A1(\__dut__.__BoundaryScanRegister_input__0__.sout ),
    .S(\__dut__.shift ),
    .X(\__dut__._01_ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._11_  (
    .A0(shift_amt[0]),
    .A1(\__dut__.__BoundaryScanRegister_input__2__.sout ),
    .S(\__dut__.test ),
    .X(\__dut__.__BoundaryScanRegister_input__2__.dout )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._12_  (
    .A0(\__dut__.__BoundaryScanRegister_input__2__.dout ),
    .A1(\__dut__.__BoundaryScanRegister_input__1__.sout ),
    .S(\__dut__.shift ),
    .X(\__dut__._02_ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._13_  (
    .A0(shift_amt[1]),
    .A1(\__dut__.__BoundaryScanRegister_input__3__.sout ),
    .S(\__dut__.test ),
    .X(\__dut__.__BoundaryScanRegister_input__3__.dout )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._14_  (
    .A0(\__dut__.__BoundaryScanRegister_input__3__.dout ),
    .A1(\__dut__.__BoundaryScanRegister_input__2__.sout ),
    .S(\__dut__.shift ),
    .X(\__dut__._03_ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._15_  (
    .A0(is_sync),
    .A1(\__dut__.__BoundaryScanRegister_input__4__.sout ),
    .S(\__dut__.test ),
    .X(\__dut__.__BoundaryScanRegister_input__4__.dout )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._16_  (
    .A0(\__dut__.__BoundaryScanRegister_input__4__.dout ),
    .A1(\__dut__.__BoundaryScanRegister_input__3__.sout ),
    .S(\__dut__.shift ),
    .X(\__dut__._04_ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._17_  (
    .A0(y),
    .A1(\__dut__.__BoundaryScanRegister_output__5__.sin ),
    .S(\__dut__.shift ),
    .X(\__dut__._05_ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._18_  (
    .A0(clk),
    .A1(tck),
    .S(\__dut__.test ),
    .X(\__dut__.__uuf__.__clk_source__ )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__._19_  (
    .A0(\__dut__.__uuf__.comb_y ),
    .A1(\__dut__.__BoundaryScanRegister_input__4__.sout ),
    .S(\__dut__.shift ),
    .X(\__dut__._06_ )
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__._20_  (
    .CLK(tck),
    .D(\__dut__._04_ ),
    .Q(\__dut__.__BoundaryScanRegister_input__4__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__._21_  (
    .CLK(tck),
    .D(\__dut__._05_ ),
    .Q(\__dut__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__._22_  (
    .CLK(tck),
    .D(\__dut__._03_ ),
    .Q(\__dut__.__BoundaryScanRegister_input__3__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__._23_  (
    .CLK(tck),
    .D(\__dut__._02_ ),
    .Q(\__dut__.__BoundaryScanRegister_input__2__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__._24_  (
    .CLK(tck),
    .D(\__dut__._01_ ),
    .Q(\__dut__.__BoundaryScanRegister_input__1__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__._25_  (
    .CLK(tck),
    .D(\__dut__._00_ ),
    .Q(\__dut__.__BoundaryScanRegister_input__0__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__maj3_1 \__dut__.__uuf__._1_  (
    .A(\__dut__.__BoundaryScanRegister_input__1__.dout ),
    .B(\__dut__.__BoundaryScanRegister_input__0__.dout ),
    .C(\__dut__.__BoundaryScanRegister_input__2__.dout ),
    .X(\__dut__.__uuf__._0_ )
  );
  sky130_fd_sc_hd__xor2_1 \__dut__.__uuf__._2_  (
    .A(\__dut__.__BoundaryScanRegister_input__3__.dout ),
    .B(\__dut__.__uuf__._0_ ),
    .X(\__dut__.__uuf__.comb_y )
  );
  sky130_fd_sc_hd__mux2_1 \__dut__.__uuf__._3_  (
    .A0(\__dut__.__uuf__.comb_y ),
    .A1(\__dut__.__BoundaryScanRegister_output__5__.sin ),
    .S(\__dut__.__BoundaryScanRegister_input__4__.dout ),
    .X(y)
  );
  sky130_fd_sc_hd__dfrtp_1 \__dut__.__uuf__._4_  (
    .CLK(\__dut__.__uuf__.__clk_source__ ),
    .D(\__dut__._06_ ),
    .Q(\__dut__.__BoundaryScanRegister_output__5__.sin ),
    .RESET_B(rst_n)
  );
endmodule

