/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-03 09:02:55
*/

module LUT
(
  clk,
  rst_n,
  in,
  shift_amt,
  is_sync,
  y,
  _4_,
  \_4_.d 
);

  input _4_;
  output \_4_.d ;
  wire _0_;
  input clk;
  wire clk;
  wire comb_y;
  input [1:0] in;
  wire [1:0] in;
  input is_sync;
  wire is_sync;
  input rst_n;
  wire rst_n;
  input [1:0] shift_amt;
  wire [1:0] shift_amt;
  output y;
  wire y;
  wire y_reg;

  sky130_fd_sc_hd__maj3_1
  _1_
  (
    .A(in[1]),
    .B(in[0]),
    .C(shift_amt[0]),
    .X(_0_)
  );


  sky130_fd_sc_hd__xor2_1
  _2_
  (
    .A(shift_amt[1]),
    .B(_0_),
    .X(comb_y)
  );


  sky130_fd_sc_hd__mux2_1
  _3_
  (
    .A0(comb_y),
    .A1(y_reg),
    .S(is_sync),
    .X(y)
  );

  assign y_reg = _4_;
  assign \_4_.d  = comb_y;

endmodule

