/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-03 11:20:29
*/

`include "custom_cells.v"
`include "LUT_netlist.v.jtag.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    wire[0:0] \y ;
    reg[0:0] \tdi ;
    reg[0:0] \trst ;
    reg[0:0] \is_sync ;
    reg[0:0] \clk ;
    reg[0:0] \tms ;
    reg[1:0] \shift_amt ;
    wire[0:0] \tdo ;
    reg[1:0] \in ;
    wire[0:0] \tdo_paden_o ;
    reg[0:0] \rst_n ;
    reg[0:0] \tck ;


    always #(`CLOCK_PERIOD / 2) clk = ~clk;
    always #(`CLOCK_PERIOD / 2) tck = ~tck;

    LUT uut(
        .\y ( \y ) , .\tdi ( \tdi ) , .\trst ( \trst ) , .\is_sync ( \is_sync ) , .\clk ( \clk ) , .\tms ( \tms ) , .\shift_amt ( \shift_amt ) , .\tdo ( \tdo ) , .\in ( \in ) , .\tdo_paden_o ( \tdo_paden_o ) , .\rst_n ( \rst_n ) , .\tck ( \tck ) 
    );    

    integer i;

    wire[6:0] __serializable__ =
        7'b1001010;
    reg[6:0] __serial__;

    wire[7:0] __tmsPattern__ = 8'b 01100110;
    wire[3:0] __preload_chain__ = 4'b0011;

    wire __tdo_pad_out__ = tdo_paden_o ? 1'bz : tdo;

    initial begin
        `ifdef VCD
            $dumpfile("dut.vcd");
            $dumpvars(0, testbench);
        `endif
        \clk = 0 ;
        \rst_n = 0 ;
        \in = 0 ;
        \shift_amt = 0 ;
        \is_sync = 0 ;
        \tms = 0 ;
        \tck = 0 ;
        \tdi = 0 ;
        \trst = 0 ;

        tms = 1;
        #(`CLOCK_PERIOD) ;
        rst_n = ~rst_n;
        trst = 1;        
        #(`CLOCK_PERIOD) ;

        /*
            Test PreloadChain Instruction
        */
        shiftIR(__preload_chain__);
        enterShiftDR();

        for (i = 0; i < 7; i = i + 1) begin
            tdi = __serializable__[i];
            #(`CLOCK_PERIOD) ;
        end
        for(i = 0; i< 7; i = i + 1) begin
            __serial__[i] = __tdo_pad_out__;
            #(`CLOCK_PERIOD) ;
        end 

        if(__serial__ !== __serializable__) begin
            $error("EXECUTING_PRELOAD_CHAIN_INST_FAILED");
            $finish;
        end
        exitDR();

        $display("SUCCESS_STRING");
        $finish;
    end

    task shiftIR;
        input[3:0] __instruction__;
        integer i;
        begin
            for (i = 0; i< 5; i = i + 1) begin
                tms = __tmsPattern__[i];
                #(`CLOCK_PERIOD) ;
            end

            // At shift-IR: shift new instruction on tdi line
            for (i = 0; i < 4; i = i + 1) begin
                tdi = __instruction__[i];
                if(i == 3) begin
                    tms = __tmsPattern__[5];     // exit-ir
                end
                #(`CLOCK_PERIOD) ;
            end

            tms = __tmsPattern__[6];     // update-ir 
            #(`CLOCK_PERIOD) ;
            tms = __tmsPattern__[7];     // run test-idle
            #(`CLOCK_PERIOD * 3) ;
        end
    endtask

    task enterShiftDR;
        begin
            tms = 1;     // select DR
            #(`CLOCK_PERIOD) ;
            tms = 0;     // capture DR -- shift DR
            #(`CLOCK_PERIOD * 2) ;
        end
    endtask

    task exitDR;
        begin
            tms = 1;     // Exit DR -- update DR
            #(`CLOCK_PERIOD * 2) ;
            tms = 0;     // Run test-idle
            #(`CLOCK_PERIOD) ;
        end
    endtask
endmodule
