/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-03 10:01:31
*/
/* FAULT METADATA: '{"shift":"shift","sin":"sin","boundaryCount":6,"internalCount":1,"sout":"sout","order":[{"kind":"input","name":"in","width":2,"ordinal":0},{"kind":"input","name":"shift_amt","width":2,"ordinal":0},{"kind":"input","name":"is_sync","width":1,"ordinal":0},{"kind":"dff","name":"_4_","width":1,"ordinal":0},{"kind":"output","name":"y","width":1,"ordinal":0}]}' END FAULT METADATA */
/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module LUT(clk, rst_n, in, shift_amt, is_sync, y, sin, shift, sout, tck, test);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_input__1__.dout ;
  wire \__BoundaryScanRegister_input__1__.sout ;
  wire \__BoundaryScanRegister_input__2__.dout ;
  wire \__BoundaryScanRegister_input__2__.sout ;
  wire \__BoundaryScanRegister_input__3__.dout ;
  wire \__BoundaryScanRegister_input__3__.sout ;
  wire \__BoundaryScanRegister_input__4__.dout ;
  wire \__BoundaryScanRegister_input__4__.sout ;
  wire \__BoundaryScanRegister_output__5__.sin ;
  wire \__uuf__._0_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.comb_y ;
  input clk;
  wire clk;
  input [1:0] in;
  wire [1:0] in;
  input is_sync;
  wire is_sync;
  input rst_n;
  wire rst_n;
  input shift;
  wire shift;
  input [1:0] shift_amt;
  wire [1:0] shift_amt;
  input sin;
  wire sin;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  output y;
  wire y;
  sky130_fd_sc_hd__mux2_1 _07_ (
    .A0(in[0]),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .X(\__BoundaryScanRegister_input__0__.dout )
  );
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(\__BoundaryScanRegister_input__0__.dout ),
    .A1(sin),
    .S(shift),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(in[1]),
    .A1(\__BoundaryScanRegister_input__1__.sout ),
    .S(test),
    .X(\__BoundaryScanRegister_input__1__.dout )
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(\__BoundaryScanRegister_input__1__.dout ),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _11_ (
    .A0(shift_amt[0]),
    .A1(\__BoundaryScanRegister_input__2__.sout ),
    .S(test),
    .X(\__BoundaryScanRegister_input__2__.dout )
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(\__BoundaryScanRegister_input__2__.dout ),
    .A1(\__BoundaryScanRegister_input__1__.sout ),
    .S(shift),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(shift_amt[1]),
    .A1(\__BoundaryScanRegister_input__3__.sout ),
    .S(test),
    .X(\__BoundaryScanRegister_input__3__.dout )
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(\__BoundaryScanRegister_input__3__.dout ),
    .A1(\__BoundaryScanRegister_input__2__.sout ),
    .S(shift),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(is_sync),
    .A1(\__BoundaryScanRegister_input__4__.sout ),
    .S(test),
    .X(\__BoundaryScanRegister_input__4__.dout )
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(\__BoundaryScanRegister_input__4__.dout ),
    .A1(\__BoundaryScanRegister_input__3__.sout ),
    .S(shift),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(y),
    .A1(\__BoundaryScanRegister_output__5__.sin ),
    .S(shift),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(clk),
    .A1(tck),
    .S(test),
    .X(\__uuf__.__clk_source__ )
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(\__uuf__.comb_y ),
    .A1(\__BoundaryScanRegister_input__4__.sout ),
    .S(shift),
    .X(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(tck),
    .D(_04_),
    .Q(\__BoundaryScanRegister_input__4__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(tck),
    .D(_05_),
    .Q(sout),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(tck),
    .D(_03_),
    .Q(\__BoundaryScanRegister_input__3__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(tck),
    .D(_02_),
    .Q(\__BoundaryScanRegister_input__2__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _24_ (
    .CLK(tck),
    .D(_01_),
    .Q(\__BoundaryScanRegister_input__1__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(tck),
    .D(_00_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__maj3_1 \__uuf__._1_  (
    .A(\__BoundaryScanRegister_input__1__.dout ),
    .B(\__BoundaryScanRegister_input__0__.dout ),
    .C(\__BoundaryScanRegister_input__2__.dout ),
    .X(\__uuf__._0_ )
  );
  sky130_fd_sc_hd__xor2_1 \__uuf__._2_  (
    .A(\__BoundaryScanRegister_input__3__.dout ),
    .B(\__uuf__._0_ ),
    .X(\__uuf__.comb_y )
  );
  sky130_fd_sc_hd__mux2_1 \__uuf__._3_  (
    .A0(\__uuf__.comb_y ),
    .A1(\__BoundaryScanRegister_output__5__.sin ),
    .S(\__BoundaryScanRegister_input__4__.dout ),
    .X(y)
  );
  sky130_fd_sc_hd__dfrtp_1 \__uuf__._4_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_06_),
    .Q(\__BoundaryScanRegister_output__5__.sin ),
    .RESET_B(rst_n)
  );
endmodule

