// // Auto-generated behavioral cell models
// // Generated by build_cell_model.sh

// module sky130_fd_sc_hd__a2111oi_0 (Y, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 & A2) | B1 | C1 | D1);
// endmodule

// module sky130_fd_sc_hd__a211o_1 (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
//   output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
//   assign X = (A1 & A2) | B1 | C1;
// endmodule

// module sky130_fd_sc_hd__a21bo_1 (X, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
//   output X; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
//   assign X = (A1 & A2) | (~B1_N);
// endmodule

// module sky130_fd_sc_hd__a21boi_0 (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 & A2) | (~B1_N));
// endmodule

// module sky130_fd_sc_hd__a21o_1 (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
//   output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
//   assign X = (A1 & A2) | B1;
// endmodule

// module sky130_fd_sc_hd__a21oi_1 (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 & A2) | B1);
// endmodule

// module sky130_fd_sc_hd__a22o_1 (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
//   output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
//   assign X = (A1 & A2) | (B1 & B2);
// endmodule

// module sky130_fd_sc_hd__a22oi_1 (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 & A2) | (B1 & B2));
// endmodule

// module sky130_fd_sc_hd__and2_0 (X, A, B, VPWR, VGND, VPB, VNB);
//   output X; input A, B, VPWR, VGND, VPB, VNB;
//   assign X = A & B;
// endmodule

// module sky130_fd_sc_hd__and3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign X = A & B & C;
// endmodule

// module sky130_fd_sc_hd__and4_1 (X, A, B, C, D, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
//   assign X = A & B & C & D;
// endmodule

// module sky130_fd_sc_hd__buf_1 (X, A, VPWR, VGND, VPB, VNB);
//   output X; input A, VPWR, VGND, VPB, VNB;
//   assign X = A;
// endmodule

// module sky130_fd_sc_hd__clkinv_1 (Y, A, VPWR, VGND, VPB, VNB);
//   output Y; input A, VPWR, VGND, VPB, VNB;
//   assign Y = ~A;
// endmodule

// module sky130_fd_sc_hd__dfrtp_1 (Q, CLK, D, RESET_B, VPWR, VGND, VPB, VNB);
//   output Q; input CLK, D, RESET_B, VPWR, VGND, VPB, VNB;
//   reg Q;
//   always @(posedge CLK or negedge RESET_B)
//     if (!RESET_B) Q <= 0; else Q <= D;
// endmodule

// module sky130_fd_sc_hd__dfstp_1 (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
//   output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
//   reg Q;
//   always @(posedge CLK or negedge SET_B)
//     if (!SET_B) Q <= 1; else Q <= D;
// endmodule

// module sky130_fd_sc_hd__dfstp_2 (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
//   output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
//   reg Q;
//   always @(posedge CLK or negedge SET_B)
//     if (!SET_B) Q <= 1; else Q <= D;
// endmodule

// module sky130_fd_sc_hd__dfxtp_1 (Q, CLK, D, VPWR, VGND, VPB, VNB);
//   output Q; input CLK, D, VPWR, VGND, VPB, VNB;
//   reg Q;
//   always @(posedge CLK) Q <= D;
// endmodule

// module sky130_fd_sc_hd__lpflow_inputiso1p_1 (X, A, SLEEP, VPWR, VGND, VPB, VNB);
//   output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
//   assign X = A & SLEEP;
// endmodule

// module sky130_fd_sc_hd__lpflow_isobufsrc_1 (X, A, SLEEP, VPWR, VGND, VPB, VNB);
//   output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
//   assign X = A;
// endmodule

// module sky130_fd_sc_hd__maj3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign X = (A & B) | (B & C) | (A & C);
// endmodule

// module sky130_fd_sc_hd__mux2_1 (X, A0, A1, S, VPWR, VGND, VPB, VNB);
//   output X; input A0, A1, S, VPWR, VGND, VPB, VNB;
//   assign X = S ? A1 : A0;
// endmodule

// module sky130_fd_sc_hd__mux2i_1 (Y, A0, A1, S, VPWR, VGND, VPB, VNB);
//   output Y; input A0, A1, S, VPWR, VGND, VPB, VNB;
//   assign Y = ~(S ? A1 : A0);
// endmodule

// module sky130_fd_sc_hd__mux4_2 (X, A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB);
//   output X; input A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB;
//   assign X = S1 ? (S0 ? A3 : A2) : (S0 ? A1 : A0);
// endmodule

// module sky130_fd_sc_hd__nand2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A & B);
// endmodule

// module sky130_fd_sc_hd__nand2b_1 (Y, A_N, B, VPWR, VGND, VPB, VNB);
//   output Y; input A_N, B, VPWR, VGND, VPB, VNB;
//   assign Y = ~((~A_N) & B);
// endmodule

// module sky130_fd_sc_hd__nand3_1 (Y, A, B, C, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A & B & C);
// endmodule

// module sky130_fd_sc_hd__nand4_1 (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A & B & C & D);
// endmodule

// module sky130_fd_sc_hd__nor2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A | B);
// endmodule

// module sky130_fd_sc_hd__nor3_1 (Y, A, B, C, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A | B | C);
// endmodule

// module sky130_fd_sc_hd__nor4_1 (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A | B | C | D);
// endmodule

// module sky130_fd_sc_hd__nor4b_1 (Y, A, B, C, D_N, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A | B | C | (~D_N));
// endmodule

// module sky130_fd_sc_hd__o21a_1 (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
//   output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
//   assign X = (A1 | A2) & B1;
// endmodule

// module sky130_fd_sc_hd__o21ai_0 (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 | A2) & B1);
// endmodule

// module sky130_fd_sc_hd__o22a_1 (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
//   output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
//   assign X = (A1 | A2) & (B1 | B2);
// endmodule

// module sky130_fd_sc_hd__o22ai_1 (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 | A2) & (B1 | B2));
// endmodule

// module sky130_fd_sc_hd__o31ai_1 (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
//   output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
//   assign Y = ~((A1 | A2 | A3) & B1);
// endmodule

// module sky130_fd_sc_hd__or3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign X = A | B | C;
// endmodule

// module sky130_fd_sc_hd__or4_1 (X, A, B, C, D, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
//   assign X = A | B | C | D;
// endmodule

// module sky130_fd_sc_hd__xnor2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
//   output Y; input A, B, VPWR, VGND, VPB, VNB;
//   assign Y = ~(A ^ B);
// endmodule

// module sky130_fd_sc_hd__xnor3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign X = ~(A ^ B ^ C);
// endmodule

// module sky130_fd_sc_hd__xor2_1 (X, A, B, VPWR, VGND, VPB, VNB);
//   output X; input A, B, VPWR, VGND, VPB, VNB;
//   assign X = A ^ B;
// endmodule

// module sky130_fd_sc_hd__xor3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
//   output X; input A, B, C, VPWR, VGND, VPB, VNB;
//   assign X = A ^ B ^ C;
// endmodule


// ===========================================================================
// riscv_custom_cells_complete.v
// Complete behavioral cell models for SKY130 HD cells used in ATPG
// Includes original cells + all 35 missing cells
// ===========================================================================

// ── Original cells ──────────────────────────────────────────────────────────

module sky130_fd_sc_hd__a2111oi_0 (Y, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1 | C1 | D1);
endmodule

module sky130_fd_sc_hd__a211o_1 (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1 | C1;
endmodule

module sky130_fd_sc_hd__a21bo_1 (X, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (~B1_N);
endmodule

module sky130_fd_sc_hd__a21boi_0 (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (~B1_N));
endmodule

module sky130_fd_sc_hd__a21o_1 (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1;
endmodule

module sky130_fd_sc_hd__a21oi_1 (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1);
endmodule

module sky130_fd_sc_hd__a22o_1 (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (B1 & B2);
endmodule

module sky130_fd_sc_hd__a22oi_1 (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2));
endmodule

module sky130_fd_sc_hd__and2_0 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A & B;
endmodule

module sky130_fd_sc_hd__and3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A & B & C;
endmodule

module sky130_fd_sc_hd__and4_1 (X, A, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = A & B & C & D;
endmodule

module sky130_fd_sc_hd__buf_1 (X, A, VPWR, VGND, VPB, VNB);
  output X; input A, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule

module sky130_fd_sc_hd__clkinv_1 (Y, A, VPWR, VGND, VPB, VNB);
  output Y; input A, VPWR, VGND, VPB, VNB;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__dfrtp_1 (Q, CLK, D, RESET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, RESET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 0; else Q <= D;
endmodule

module sky130_fd_sc_hd__dfstp_1 (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge SET_B)
    if (!SET_B) Q <= 1; else Q <= D;
endmodule

module sky130_fd_sc_hd__dfstp_2 (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge SET_B)
    if (!SET_B) Q <= 1; else Q <= D;
endmodule

module sky130_fd_sc_hd__dfxtp_1 (Q, CLK, D, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK) Q <= D;
endmodule

module sky130_fd_sc_hd__lpflow_inputiso1p_1 (X, A, SLEEP, VPWR, VGND, VPB, VNB);
  output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
  assign X = A & SLEEP;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_1 (X, A, SLEEP, VPWR, VGND, VPB, VNB);
  output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule

module sky130_fd_sc_hd__maj3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = (A & B) | (B & C) | (A & C);
endmodule

module sky130_fd_sc_hd__mux2_1 (X, A0, A1, S, VPWR, VGND, VPB, VNB);
  output X; input A0, A1, S, VPWR, VGND, VPB, VNB;
  assign X = S ? A1 : A0;
endmodule

module sky130_fd_sc_hd__mux2i_1 (Y, A0, A1, S, VPWR, VGND, VPB, VNB);
  output Y; input A0, A1, S, VPWR, VGND, VPB, VNB;
  assign Y = ~(S ? A1 : A0);
endmodule

module sky130_fd_sc_hd__mux4_2 (X, A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB);
  output X; input A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB;
  assign X = S1 ? (S0 ? A3 : A2) : (S0 ? A1 : A0);
endmodule

module sky130_fd_sc_hd__nand2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B);
endmodule

module sky130_fd_sc_hd__nand2b_1 (Y, A_N, B, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B);
endmodule

module sky130_fd_sc_hd__nand3_1 (Y, A, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B & C);
endmodule

module sky130_fd_sc_hd__nand4_1 (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B & C & D);
endmodule

module sky130_fd_sc_hd__nor2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B);
endmodule

module sky130_fd_sc_hd__nor3_1 (Y, A, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C);
endmodule

module sky130_fd_sc_hd__nor4_1 (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C | D);
endmodule

module sky130_fd_sc_hd__nor4b_1 (Y, A, B, C, D_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C | (~D_N));
endmodule

module sky130_fd_sc_hd__o21a_1 (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & B1;
endmodule

module sky130_fd_sc_hd__o21ai_0 (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & B1);
endmodule

module sky130_fd_sc_hd__o22a_1 (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & (B1 | B2);
endmodule

module sky130_fd_sc_hd__o22ai_1 (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (B1 | B2));
endmodule

module sky130_fd_sc_hd__o31ai_1 (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & B1);
endmodule

module sky130_fd_sc_hd__or3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A | B | C;
endmodule

module sky130_fd_sc_hd__or4_1 (X, A, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = A | B | C | D;
endmodule

module sky130_fd_sc_hd__xnor2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A ^ B);
endmodule

module sky130_fd_sc_hd__xnor3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = ~(A ^ B ^ C);
endmodule

module sky130_fd_sc_hd__xor2_1 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A ^ B;
endmodule

module sky130_fd_sc_hd__xor3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A ^ B ^ C;
endmodule

// ── Missing cells — added below ─────────────────────────────────────────────

// a2111o_1: (A1&A2) | B1 | C1 | D1
module sky130_fd_sc_hd__a2111o_1 (X, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1 | C1 | D1;
endmodule

// a211oi_1: ~((A1&A2) | B1 | C1)
module sky130_fd_sc_hd__a211oi_1 (Y, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1 | C1);
endmodule

// a221o_1: (A1&A2) | (B1&B2) | C1
module sky130_fd_sc_hd__a221o_1 (X, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (B1 & B2) | C1;
endmodule

// a221oi_1: ~((A1&A2) | (B1&B2) | C1)
module sky130_fd_sc_hd__a221oi_1 (Y, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2) | C1);
endmodule

// a222oi_1: ~((A1&A2) | (B1&B2) | (C1&C2))
module sky130_fd_sc_hd__a222oi_1 (Y, A1, A2, B1, B2, C1, C2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, C2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2) | (C1 & C2));
endmodule

// a2bb2oi_1: ~((~A1_N & ~A2_N) | (B1 & B2))
module sky130_fd_sc_hd__a2bb2oi_1 (Y, A1_N, A2_N, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1_N, A2_N, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A1_N & ~A2_N) | (B1 & B2));
endmodule

// a311o_1: (A1&A2&A3) | B1 | C1
module sky130_fd_sc_hd__a311o_1 (X, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | B1 | C1;
endmodule

// a311oi_1: ~((A1&A2&A3) | B1 | C1)
module sky130_fd_sc_hd__a311oi_1 (Y, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | B1 | C1);
endmodule

// a31o_1: (A1&A2&A3) | B1
module sky130_fd_sc_hd__a31o_1 (X, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | B1;
endmodule

// a31oi_1: ~((A1&A2&A3) | B1)
module sky130_fd_sc_hd__a31oi_1 (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | B1);
endmodule

// a32oi_1: ~((A1&A2&A3) | (B1&B2))
module sky130_fd_sc_hd__a32oi_1 (Y, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | (B1 & B2));
endmodule

// a41oi_1: ~((A1&A2&A3&A4) | B1)
module sky130_fd_sc_hd__a41oi_1 (Y, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3 & A4) | B1);
endmodule

// and3b_1: (~A_N) & B & C
module sky130_fd_sc_hd__and3b_1 (X, A_N, B, C, VPWR, VGND, VPB, VNB);
  output X; input A_N, B, C, VPWR, VGND, VPB, VNB;
  assign X = (~A_N) & B & C;
endmodule

// and4b_1: (~A_N) & B & C & D
module sky130_fd_sc_hd__and4b_1 (X, A_N, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A_N, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = (~A_N) & B & C & D;
endmodule

// nand3b_1: ~((~A_N) & B & C)
module sky130_fd_sc_hd__nand3b_1 (Y, A_N, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B & C);
endmodule

// nand4b_1: ~((~A_N) & B & C & D)
module sky130_fd_sc_hd__nand4b_1 (Y, A_N, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B & C & D);
endmodule

// nand4bb_1: ~((~A_N) & (~B_N) & C & D)
module sky130_fd_sc_hd__nand4bb_1 (Y, A_N, B_N, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B_N, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & (~B_N) & C & D);
endmodule

// nor2b_1: ~(A | (~B_N))
module sky130_fd_sc_hd__nor2b_1 (Y, A, B_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | (~B_N));
endmodule

// nor3b_1: ~(A | B | (~C_N))
module sky130_fd_sc_hd__nor3b_1 (Y, A, B, C_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | (~C_N));
endmodule

// nor4bb_1: ~(A | B | (~C_N) | (~D_N))
module sky130_fd_sc_hd__nor4bb_1 (Y, A, B, C_N, D_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C_N, D_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | (~C_N) | (~D_N));
endmodule

// o2111ai_1: ~((A1|A2) & B1 & C1 & D1)
module sky130_fd_sc_hd__o2111ai_1 (Y, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & B1 & C1 & D1);
endmodule

// o211a_1: (A1|A2) & B1 & C1  -- note: same as o21a with extra C1 AND
// SKY130 naming: o211 = OR2-AND-AND-AND chain
// X = ((A1|A2) & B1) | C1
module sky130_fd_sc_hd__o211a_1 (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & B1) | C1;
endmodule

// o211ai_1: ~(((A1|A2) & B1) | C1)
module sky130_fd_sc_hd__o211ai_1 (Y, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~(((A1 | A2) & B1) | C1);
endmodule

// o21ba_1: (A1|A2) & (~B1_N)
module sky130_fd_sc_hd__o21ba_1 (X, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & (~B1_N);
endmodule

// o21bai_1: ~((A1|A2) & (~B1_N))
module sky130_fd_sc_hd__o21bai_1 (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (~B1_N));
endmodule

// o221a_1: ((A1|A2) & (B1|B2)) | C1
module sky130_fd_sc_hd__o221a_1 (X, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & (B1 | B2)) | C1;
endmodule

// o221ai_1: ~(((A1|A2) & (B1|B2)) | C1)
module sky130_fd_sc_hd__o221ai_1 (Y, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~(((A1 | A2) & (B1 | B2)) | C1);
endmodule

// o311a_1: ((A1|A2|A3) & B1) | C1
module sky130_fd_sc_hd__o311a_1 (X, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2 | A3) & B1) | C1;
endmodule

// o311ai_0: ~(((A1|A2|A3) & B1) | C1)
module sky130_fd_sc_hd__o311ai_0 (Y, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~(((A1 | A2 | A3) & B1) | C1);
endmodule

// o31a_1: (A1|A2|A3) & B1
module sky130_fd_sc_hd__o31a_1 (X, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2 | A3) & B1;
endmodule

// o32a_1: ((A1|A2|A3) & (B1|B2))
module sky130_fd_sc_hd__o32a_1 (X, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2 | A3) & (B1 | B2);
endmodule

// o32ai_1: ~((A1|A2|A3) & (B1|B2))
module sky130_fd_sc_hd__o32ai_1 (Y, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & (B1 | B2));
endmodule

// o41a_1: (A1|A2|A3|A4) & B1
module sky130_fd_sc_hd__o41a_1 (X, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2 | A3 | A4) & B1;
endmodule

// or3b_1: A | B | (~C_N)
module sky130_fd_sc_hd__or3b_1 (X, A, B, C_N, VPWR, VGND, VPB, VNB);
  output X; input A, B, C_N, VPWR, VGND, VPB, VNB;
  assign X = A | B | (~C_N);
endmodule

// or4b_1: A | B | C | (~D_N)
module sky130_fd_sc_hd__or4b_1 (X, A, B, C, D_N, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
  assign X = A | B | C | (~D_N);
endmodule

// buf_2 — used by synthesis driving cell
module sky130_fd_sc_hd__buf_2 (X, A, VPWR, VGND, VPB, VNB);
  output X; input A, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule

// inv_1 — common inverter variant
module sky130_fd_sc_hd__inv_1 (Y, A, VPWR, VGND, VPB, VNB);
  output Y; input A, VPWR, VGND, VPB, VNB;
  assign Y = ~A;
endmodule

// dfxtp_2 — 2x drive flip-flop
module sky130_fd_sc_hd__dfxtp_2 (Q, CLK, D, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK) Q <= D;
endmodule

// dfrtp_2 — 2x drive reset flip-flop
module sky130_fd_sc_hd__dfrtp_2 (Q, CLK, D, RESET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, RESET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 0; else Q <= D;
endmodule

// dfrtp_4 — 4x drive reset flip-flop
module sky130_fd_sc_hd__dfrtp_4 (Q, CLK, D, RESET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, RESET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 0; else Q <= D;
endmodule

// and2_1 — 1x drive AND2
module sky130_fd_sc_hd__and2_1 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A & B;
endmodule

// or2_0 — OR2
module sky130_fd_sc_hd__or2_0 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A | B;
endmodule

// or2_1 — OR2 1x drive
module sky130_fd_sc_hd__or2_1 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A | B;
endmodule

// nand2_2 — 2x drive NAND2
module sky130_fd_sc_hd__nand2_2 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B);
endmodule

// nor2_2 — 2x drive NOR2
module sky130_fd_sc_hd__nor2_2 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B);
endmodule

// o2111a_1: ((A1|A2) & B1 & C1) | D1
module sky130_fd_sc_hd__o2111a_1 (X, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & B1 & C1) | D1;
endmodule

// a32o_1: (A1&A2&A3) | (B1&B2)
module sky130_fd_sc_hd__a32o_1 (X, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | (B1 & B2);
endmodule

// clkbuf_1 — clock buffer
module sky130_fd_sc_hd__clkbuf_1 (X, A, VPWR, VGND, VPB, VNB);
  output X; input A, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule

// clkbuf_2 — clock buffer 2x
module sky130_fd_sc_hd__clkbuf_2 (X, A, VPWR, VGND, VPB, VNB);
  output X; input A, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule

// ebufn_2 — tri-state buffer (model as pass-through for ATPG)
module sky130_fd_sc_hd__ebufn_2 (Z, A, TE_B, VPWR, VGND, VPB, VNB);
  output Z; input A, TE_B, VPWR, VGND, VPB, VNB;
  assign Z = TE_B ? 1'bz : A;
endmodule

module sky130_fd_sc_hd__a41o_1 (X, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3 & A4) | B1;
endmodule
 
// o2bb2ai_1: ~((~A1_N | ~A2_N) & (B1 | B2))
module sky130_fd_sc_hd__o2bb2ai_1 (Y, A1_N, A2_N, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1_N, A2_N, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A1_N | ~A2_N) & (B1 | B2));
endmodule
 
// o41ai_1: ~((A1|A2|A3|A4) & B1)
module sky130_fd_sc_hd__o41ai_1 (Y, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3 | A4) & B1);
endmodule
 