/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module LUT(clk, rst_n, in, shift_amt, is_sync, y);
  wire _0_;
  input clk;
  wire clk;
  wire comb_y;
  input [1:0] in;
  wire [1:0] in;
  input is_sync;
  wire is_sync;
  wire [3:0] lut0;
  wire [3:0] lut1;
  wire [3:0] lut2;
  wire [3:0] lut3;
  input rst_n;
  wire rst_n;
  input [1:0] shift_amt;
  wire [1:0] shift_amt;
  output y;
  wire y;
  wire y_reg;
  sky130_fd_sc_hd__maj3_1 _1_ (
    .A(in[0]),
    .B(in[1]),
    .C(shift_amt[0]),
    .X(_0_)
  );
  sky130_fd_sc_hd__xor2_1 _2_ (
    .A(shift_amt[1]),
    .B(_0_),
    .X(comb_y)
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(comb_y),
    .A1(y_reg),
    .S(is_sync),
    .X(y)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(comb_y),
    .Q(y_reg),
    .RESET_B(rst_n)
  );
  assign lut0 = 4'hc;
  assign lut1 = 4'h6;
  assign lut2 = 4'h6;
  assign lut3 = 4'h3;
endmodule
